"""Build data/towns.json, the small per-town file the free check loads.

Inputs (each regenerated by its own script, see their headers):
  data/town_tax_options.json  <- tools/build_town_tax_options.py  (DLS local-options reports)
  data/town_services.json     <- tools/build_town_services.py     (agency directories; optional)

Output: data/towns.json
  {"meta": {...}, "agencies": {id: {n, p, u}}, "towns": {"Methuen": {...}, ...}}

Per-town keys (all optional; absent = "not shown by the source", NEVER "not offered"):
  c     elderly exemption clause on file with DLS: "41C" | "41C½" | "41B"
  age   41C qualifying age on file with DLS (65/66/67/70). Matched towns' own docs in 6 of 7 spot checks.
  ss    surviving-spouse / 70+ clause: "17D" | "17C" | "17C½"
  b37   true = Clause 37A (blind, $500) adopted
  res   residential exemption percent
  mt    true = home-rule means-tested senior exemption
  cpa   true = Community Preservation Act adopted
  cpas  true = CPA low/moderate-income (incl. senior) surcharge exemption adopted
  d41   number of Clause 41A deferrals granted in the latest fiscal year DLS shows (>0 only)
  fuel/asap/shine/rta  agency id (or list of ids) -> "agencies" ({n name, p phone, u url, a areas})
  ride  MBTA The RIDE paratransit coverage: "full" | "partial"
  coa   {n, p, u} council on aging

Deliberately NOT included: the 41C dollar amount and income/asset limits on file with DLS. They matched
the town's own current documents in only 3 of 7 spot checks (see town_tax_options.json "spot_checks"),
so showing them as "your amount" would be wrong too often.

Run: python3 tools/build_towns.py
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TAX = os.path.join(ROOT, "data", "town_tax_options.json")
SVC = os.path.join(ROOT, "data", "town_services.json")
OUT = os.path.join(ROOT, "data", "towns.json")


def main():
    tax = json.load(open(TAX))
    towns = {}
    for name, v in tax["towns"].items():
        t = {}
        clause = v.get("elderly_exemption_clause")
        if clause:
            t["c"] = clause.replace(" 1/2", "½")
        if v.get("clause_41c_age_on_file") in (65, 66, 67, 68, 69, 70):
            t["age"] = v["clause_41c_age_on_file"]
        if v.get("surviving_spouse_clause"):
            t["ss"] = v["surviving_spouse_clause"].replace(" 1/2", "½")
        if v.get("clause_37a_blind_adopted"):
            t["b37"] = True
        if v.get("residential_exemption_pct"):
            t["res"] = v["residential_exemption_pct"]
        if v.get("senior_means_tested_exemption"):
            t["mt"] = True
        if v.get("cpa_adopted"):
            t["cpa"] = True
        if v.get("cpa_exempt_low_income_and_senior"):
            t["cpas"] = True
        if (v.get("deferral_41a_count_latest_fy") or 0) > 0:
            t["d41"] = v["deferral_41a_count_latest_fy"]
        towns[name] = t

    agencies, agency_keys = {}, {}
    svc_meta = None
    if os.path.exists(SVC):
        svc = json.load(open(SVC))
        svc_meta = {"fetched": svc.get("fetched"), "sources": list((svc.get("sources") or {}).keys())}

        def agency_id(name, phone=None, url=None, areas=None):
            if not name:
                return None
            rec = {"n": name}
            if phone: rec["p"] = phone
            if url: rec["u"] = url
            if areas: rec["a"] = areas
            sig = json.dumps(rec, sort_keys=True)
            if sig not in agency_keys:          # short ids keep towns.json small
                agency_keys[sig] = str(len(agency_keys) + 1)
                agencies[agency_keys[sig]] = rec
            return agency_keys[sig]

        def ids(xs):
            out = [i for i in xs if i]
            return (out if len(out) > 1 else out[0]) if out else None

        for name, s in (svc.get("towns") or {}).items():
            if name not in towns:
                print(f"WARNING: services town not in DLS list: {name!r}", file=sys.stderr)
                continue
            t = towns[name]
            f = s.get("fuel") or {}
            v = agency_id(f.get("agency"), f.get("phone"), f.get("url"))
            if v: t["fuel"] = v
            v = ids([agency_id(x.get("name"), x.get("phone"), x.get("url"), x.get("areas")) for x in (s.get("asap") or [])])
            if v: t["asap"] = v
            sh = s.get("shine") or {}
            v = agency_id(f"SHINE ({sh['office']})" if sh.get("office") else None, sh.get("phone"))
            if v: t["shine"] = v
            v = ids([agency_id(x.get("name"), x.get("phone"), x.get("url")) for x in (s.get("rta") or [])])
            if v: t["rta"] = v
            if s.get("mbta_the_ride") in ("full", "partial"):
                t["ride"] = s["mbta_the_ride"]
            coa = s.get("coa")
            if isinstance(coa, dict) and (coa.get("name") or coa.get("phone")):
                t["coa"] = {k2: coa[k1] for k1, k2 in (("name", "n"), ("phone", "p"), ("url", "u")) if coa.get(k1)}

    # Positive controls: the instrument must see things we know exist.
    assert towns["Methuen"].get("c") == "41C", "control: Methuen 41C missing"
    assert towns["Boston"].get("res"), "control: Boston residential exemption missing"
    assert towns["Sudbury"].get("mt"), "control: Sudbury means-tested exemption missing"
    assert len(towns) == 351, f"expected 351 towns, got {len(towns)}"
    if os.path.exists(SVC):
        assert towns["Methuen"].get("fuel") and towns["Methuen"].get("asap"), "control: Methuen agencies missing"
        assert isinstance(towns["Boston"].get("asap"), list) and len(towns["Boston"]["asap"]) == 3, "control: Boston should have 3 ASAPs"

    out = {"meta": {"tax_source": tax.get("source"), "tax_fetched": tax.get("fetched"),
                    "services": svc_meta, "built": "see git log"},
           "agencies": agencies, "towns": towns}
    s = json.dumps(out, separators=(",", ":"), ensure_ascii=False)
    open(OUT, "w").write(s)
    cov = {k: sum(1 for t in towns.values() if k in t) for k in
           ("c", "age", "ss", "b37", "res", "mt", "cpa", "cpas", "d41", "fuel", "asap", "coa", "shine", "rta", "ride")}
    print(f"wrote {OUT}: {len(s):,} bytes, {len(towns)} towns, {len(agencies)} agencies")
    print("coverage:", cov)


if __name__ == "__main__":
    main()
