"""Build data/towns.json, the small per-town file the free check loads.

Inputs (each regenerated by its own script, see their headers):
  data/town_tax_options.json  <- tools/build_town_tax_options.py  (DLS local-options reports)
  data/town_services.json     <- tools/build_town_services.py     (agency directories; optional)

Output: data/towns.json
  {"meta": {...}, "agencies": {id: {n, p, u}}, "towns": {"Methuen": {...}, ...}}

Per-town keys (all optional; absent = "not shown by the source", NEVER "not offered"):
  c     elderly exemption clause on file with DLS: "41C" | "41C½" | "41B"
  age   41C qualifying age on file with DLS (65/66/67/70). Matched towns' own docs in 6 of 7 spot checks.
  ss    surviving-spouse / 70+ clause: "17D" | "17C" | "17C½"
  b37   true = Clause 37A (blind, $500) adopted
  res   residential exemption percent
  mt    true = home-rule means-tested senior exemption
  cpa   true = Community Preservation Act adopted
  cpas  true = CPA low/moderate-income (incl. senior) surcharge exemption adopted
  d41   number of Clause 41A deferrals granted in the latest fiscal year DLS shows (>0 only)
  fuel/asap/shine/rta  agency id (or list of ids) -> "agencies" ({n name, p phone, u url, a areas})
  ride  MBTA The RIDE paratransit coverage: "full" | "partial"
  coa   {n, p, u} council on aging

Deliberately NOT included: the 41C dollar amount and income/asset limits on file with DLS. They matched
the town's own current documents in only 3 of 7 spot checks (see town_tax_options.json "spot_checks"),
so showing them as "your amount" would be wrong too often.

Run: python3 tools/build_towns.py
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TAX = os.path.join(ROOT, "data", "town_tax_options.json")
SVC = os.path.join(ROOT, "data", "town_services.json")
OUT = os.path.join(ROOT, "data", "towns.json")


def main():
    tax = json.load(open(TAX))
    towns = {}
    for name, v in tax["towns"].items():
        t = {}
        clause = v.get("elderly_exemption_clause")
        if clause:
            t["c"] = clause.replace(" 1/2", "½")
        if v.get("clause_41c_age_on_file") in (65, 66, 67, 68, 69, 70):
            t["age"] = v["clause_41c_age_on_file"]
        if v.get("surviving_spouse_clause"):
            t["ss"] = v["surviving_spouse_clause"].replace(" 1/2", "½")
        if v.get("clause_37a_blind_adopted"):
            t["b37"] = True
        if v.get("residential_exemption_pct"):
            t["res"] = v["residential_exemption_pct"]
        if v.get("senior_means_tested_exemption"):
            t["mt"] = True
        if v.get("cpa_adopted"):
            t["cpa"] = True
        if v.get("cpa_exempt_low_income_and_senior"):
            t["cpas"] = True
        if (v.get("deferral_41a_count_latest_fy") or 0) > 0:
            t["d41"] = v["deferral_41a_count_latest_fy"]
        towns[name] = t

    agencies, agency_keys = {}, {}
    svc_meta = None
    if os.path.exists(SVC):
        svc = json.load(open(SVC))
        svc_meta = {"fetched": svc.get("fetched"), "sources": list((svc.get("sources") or {}).keys())}

        def agency_id(name, phone=None, url=None, areas=None):
            if not name:
                return None
            rec = {"n": name}
            if phone: rec["p"] = phone
            if url: rec["u"] = url
            if areas: rec["a"] = areas
            sig = json.dumps(rec, sort_keys=True)
            if sig not in agency_keys:          # short ids keep towns.json small
                agency_keys[sig] = str(len(agency_keys) + 1)
                agencies[agency_keys[sig]] = rec
            return agency_keys[sig]

        def ids(xs):
            out = [i for i in xs if i]
            return (out if len(out) > 1 else out[0]) if out else None

        for name, s in (svc.get("towns") or {}).items():
            if name not in towns:
                print(f"WARNING: services town not in DLS list: {name!r}", file=sys.stderr)
                continue
            t = towns[name]
            f = s.get("fuel") or {}
            v = agency_id(f.get("agency"), f.get("phone"), f.get("url"))
            if v: t["fuel"] = v
            v = ids([agency_id(x.get("name"), x.get("phone"), x.get("url"), x.get("areas")) for x in (s.get("asap") or [])])
            if v: t["asap"] = v
            sh = s.get("shine") or {}
            v = agency_id(f"SHINE ({sh['office']})" if sh.get("office") else None, sh.get("phone"))
            if v: t["shine"] = v
            v = ids([agency_id(x.get("name"), x.get("phone"), x.get("url")) for x in (s.get("rta") or [])])
            if v: t["rta"] = v
            if s.get("mbta_the_ride") in ("full", "partial"):
                t["ride"] = s["mbta_the_ride"]
            coa = s.get("coa")
            if isinstance(coa, dict) and (coa.get("name") or coa.get("phone")):
                t["coa"] = {k2: coa[k1] for k1, k2 in (("name", "n"), ("phone", "p"), ("url", "u")) if coa.get(k1)}

    # ---- Town-website facts (data/town_web/batch_*.json; 50 largest towns, researched 2026-09-25) ----
    # Conservative on purpose: numbers are shown only when current (FY2026+) and not flagged stale;
    # long/conflicting free text is dropped in favour of "ask". Each fact keeps its town source URL.
    import glob
    def num_or_none(v):
        if isinstance(v, (int, float)): return v
        m = re.fullmatch(r"\$?\s*([\d,]+(?:\.\d+)?)", str(v or "").strip())
        return float(m.group(1).replace(",", "")) if m else None
    def first_age(v):
        if isinstance(v, (int, float)): return int(v)
        m = re.search(r"\b(6[0-9]|70)\b", str(v or ""))
        return int(m.group(1)) if m else None
    def fy_of(*vals):
        for v in vals:
            m = re.search(r"FY\s?(20\d\d)", str(v or ""))
            if m: return int(m.group(1))
        return None
    def short(v, n=90):
        v = str(v or "").strip()
        return v if v and len(v) <= n and "CONFLICT" not in v.upper() and "stale" not in v.lower() else None
    web_n = 0
    for f in sorted(glob.glob(os.path.join(ROOT, "data", "town_web", "batch_*.json"))):
        for name, v in json.load(open(f))["towns"].items():
            if name not in towns:
                print(f"WARNING: town_web name not in DLS list: {name!r}", file=sys.stderr); continue
            w = {}
            wo = v.get("workoff") or {}
            if wo.get("status") in ("offered", "not_offered"):
                o = {"s": wo["status"]}
                if wo.get("source_url"): o["src"] = wo["source_url"]
                if wo["status"] == "offered":
                    mx = num_or_none(wo.get("max_dollars"))
                    if mx: o["max"] = int(mx)
                    if short(wo.get("signup_window"), 70): o["win"] = short(wo.get("signup_window"), 70)
                    if short(wo.get("apply_where"), 90): o["where"] = short(wo.get("apply_where"), 90)
                    ph = re.search(r"\(?\d{3}\)?[\s.-]?\d{3}-\d{4}", str(wo.get("contact_phone") or ""))
                    if ph: o["ph"] = ph.group(0)
                    if wo.get("stale"): o["old"] = True
                w["wo"] = o
            ex = v.get("exemption_41c") or {}
            fy = fy_of(ex.get("fiscal_year"), ex.get("date_or_fy"))
            e = {}
            amt = num_or_none(ex.get("amount_dollars"))
            amt_txt = short(ex.get("amount_dollars"), 16) if amt is None and "$" in str(ex.get("amount_dollars") or "") else None
            current = fy is not None and fy >= 2026 and not ex.get("stale")
            if current and (amt or amt_txt):
                e["amt"] = int(amt) if amt else amt_txt
                e["fy"] = fy
            a = first_age(ex.get("qualifying_age"))
            if a and not ex.get("stale"): e["age"] = a
            if e and ex.get("source_url"): e["src"] = ex["source_url"]
            if e: w["ex"] = e
            asr = v.get("assessor") or {}
            ph = re.search(r"\(?\d{3}\)?[\s.-]?\d{3}-\d{4}", str(asr.get("phone") or ""))
            if ph: w["ap"] = ph.group(0)
            if w:
                towns[name]["w"] = w; web_n += 1
    print(f"town_web facts merged for {web_n} towns")

    # Positive controls: the instrument must see things we know exist.
    assert towns["Methuen"].get("c") == "41C", "control: Methuen 41C missing"
    assert towns["Boston"].get("res"), "control: Boston residential exemption missing"
    assert towns["Sudbury"].get("mt"), "control: Sudbury means-tested exemption missing"
    assert len(towns) == 351, f"expected 351 towns, got {len(towns)}"
    if os.path.exists(SVC):
        assert towns["Methuen"].get("fuel") and towns["Methuen"].get("asap"), "control: Methuen agencies missing"
        assert isinstance(towns["Boston"].get("asap"), list) and len(towns["Boston"]["asap"]) == 3, "control: Boston should have 3 ASAPs"
    if os.path.isdir(os.path.join(ROOT, "data", "town_web")):
        mw = towns["Methuen"].get("w", {})
        assert mw.get("wo", {}).get("max") == 2000 and mw.get("ex", {}).get("age") == 65, "control: Methuen town-web facts wrong"
        assert towns["Boston"].get("w", {}).get("ex", {}).get("amt") == 1000, "control: Boston 41C amount wrong"

    out = {"meta": {"tax_source": tax.get("source"), "tax_fetched": tax.get("fetched"),
                    "services": svc_meta, "built": "see git log"},
           "agencies": agencies, "towns": towns}
    s = json.dumps(out, separators=(",", ":"), ensure_ascii=False)
    open(OUT, "w").write(s)
    cov = {k: sum(1 for t in towns.values() if k in t) for k in
           ("c", "age", "ss", "b37", "res", "mt", "cpa", "cpas", "d41", "fuel", "asap", "coa", "shine", "rta", "ride")}
    print(f"wrote {OUT}: {len(s):,} bytes, {len(towns)} towns, {len(agencies)} agencies")
    print("coverage:", cov)


if __name__ == "__main__":
    main()
